name: "Fechando automaticamente as issues"

on:
  pull_request:
    types:
      - closed
      - edited
      - synchronize

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-close-fixed-issues@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Essa issue foi fechada automaticamente pelo PR #{{ pr }}.'
