name: Release GitHub Action
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bubkoo/release-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
