name: "Criação de release"
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses:  'phips28/gh-action-bump-version@master'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'
      - uses: actions/checkout@v1
      - uses: bubkoo/release-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
